/**
 * Cut list generation.
 *
 * Generated by walking the construction graph, never hand-authored. Because
 * the picture and the numbers come from the same simulation, they cannot drift
 * apart.
 */

import { boardDimensions, type EvalResult } from '../geometry/evaluate.js';
import { bevelledWidths } from '../geometry/polygon.js';
import { SPECIES } from '../knowledge/species.js';
import type { Graph, NodeId, ShopProfile, SpeciesId, Ticks } from '../model/types.js';
import { type Dimension, dimension, formatTicks, toInches } from '../units/ticks.js';
import { analyze } from './analyze.js';
import { buildLedger, type AllowanceLedger } from './ledger.js';

const CUBIC_INCHES_PER_BOARD_FOOT = 144;

/**
 * What to set the machine to -- which is not the same as the geometry.
 *
 * Nobody sets a table saw by "cut position across the cross-section"; they set
 * a fence-to-blade distance. Reporting the geometry instead of the setting is
 * how a cut list ends up arithmetically right and practically useless.
 */
export type MachineSetting =
  | {
      readonly machine: 'tablesaw-rip';
      readonly fenceSetting: Dimension;
      readonly bevel: number;
      /**
       * Required whenever the bevel is non-zero. Standard safe practice tilts
       * the blade away from the fence so the workpiece is not trapped -- and a
       * mirrored bevel produces a mirrored pattern, which for a 3D cube means
       * the illusion never appears.
       */
      readonly bladeTiltDirection?: 'away-from-fence';
      /** A bevelled strip has two different widths; both are reported. */
      readonly widthAtTableFace: Dimension;
      readonly widthAtTopFace: Dimension;
    }
  | {
      readonly machine: 'sled-crosscut';
      readonly stopBlockSetting: Dimension;
      readonly count: number;
      readonly miter: number;
    }
  | {
      readonly machine: 'drum-sander';
      readonly targetThickness: Dimension;
      readonly passCount: number;
      readonly perPass: Dimension;
    };

export interface CutPiece {
  readonly pieceId: string;
  readonly species: SpeciesId;
  readonly quantity: number;
  readonly thickness: Dimension;
  readonly width: Dimension;
  readonly length: Dimension;
  readonly machineSetting?: MachineSetting;
}

export interface PieceGroup {
  readonly fromNode: NodeId;
  readonly operation: string;
  readonly pieces: readonly CutPiece[];
}

export interface PurchaseLine {
  readonly species: SpeciesId;
  readonly displayName: string;
  readonly boardFeet: number;
  readonly rough: { thickness: Ticks; width: Ticks; length: Ticks };
}

export interface MaterialSummary {
  readonly totalBoardFeet: number;
  /** Rough stock volume divided by finished board volume. */
  readonly endGrainMultiplier: number;
  readonly wasteFraction: number;
}

export interface CutList {
  readonly boardName: string;
  readonly finished: { width: Dimension; length: Dimension; thickness: Dimension };
  readonly purchase: readonly PurchaseLine[];
  readonly groups: readonly PieceGroup[];
  readonly ledger: AllowanceLedger;
  readonly summary: MaterialSummary;
}

export function buildCutList(
  graph: Graph,
  evaluated: EvalResult,
  shop: ShopProfile,
  options: { name: string; precision: Ticks },
): CutList {
  const a = analyze(graph);
  const dims = boardDimensions(evaluated.workpiece);
  const dim = (v: number): Dimension => dimension(v, options.precision);

  /* ---- Purchase ---------------------------------------------------------- */

  const purchase: PurchaseLine[] = a.billets.map((b) => {
    const { rough, species } = b.op;
    const boardFeet =
      (toInches(rough.thickness) * toInches(rough.width) * toInches(rough.length)) /
      CUBIC_INCHES_PER_BOARD_FOOT;
    return {
      species,
      displayName: SPECIES[species]?.name ?? species,
      boardFeet,
      rough,
    };
  });

  /* ---- Pieces ------------------------------------------------------------ */

  const groups: PieceGroup[] = [];

  for (const rip of a.rips) {
    const source = evaluated.nodeOutputs.get(rip.op.input.node)?.[rip.op.input.port];
    const stockThickness = source ? extentY(source) : 0;
    const species = source?.crossSection.faces[0]?.species ?? 'unknown';

    // Identical strips collapse into one row with a quantity, which is how a
    // cut list is actually read at the bench.
    const byWidth = new Map<number, number>();
    for (const strip of rip.op.strips) byWidth.set(strip.width, (byWidth.get(strip.width) ?? 0) + 1);

    groups.push({
      fromNode: rip.id,
      operation: rip.label ?? 'Rip to width',
      pieces: [...byWidth].map(([stripWidth, quantity], index) => {
        const bevel = rip.op.strips.find((s) => s.width === stripWidth)?.bevel ?? 0;
        const widths = bevelledWidths(stripWidth, stockThickness, bevel as never);
        const setting: MachineSetting = {
          machine: 'tablesaw-rip',
          fenceSetting: dim(stripWidth),
          bevel,
          ...(bevel === 0 ? {} : { bladeTiltDirection: 'away-from-fence' as const }),
          widthAtTableFace: dim(widths.atTableFace),
          widthAtTopFace: dim(widths.atTopFace),
        };
        return {
          pieceId: `${rip.id}-s${index}`,
          species,
          quantity,
          thickness: dim(stockThickness),
          width: dim(stripWidth),
          length: dim(source?.length ?? 0),
          machineSetting: setting,
        };
      }),
    });
  }

  for (const cut of a.crosscuts) {
    const source = evaluated.nodeOutputs.get(cut.op.input.node)?.[cut.op.input.port];
    const count = cut.op.count ?? 0;
    groups.push({
      fromNode: cut.id,
      operation: cut.label ?? 'Crosscut into slices',
      pieces: [
        {
          pieceId: `${cut.id}-slice`,
          species: 'mixed',
          quantity: count,
          thickness: dim(source ? extentY(source) : 0),
          width: dim(source ? extentX(source) : 0),
          length: dim(cut.op.sliceLength),
          machineSetting: {
            machine: 'sled-crosscut',
            stopBlockSetting: dim(cut.op.sliceLength),
            count,
            miter: cut.op.miter,
          },
        },
      ],
    });
  }

  for (const flatten of a.flattens) {
    if (flatten.op.method !== 'drumSander') continue;
    const passCount = Math.ceil(flatten.op.removePerFace / shop.drumSanderRemovalPerPass);
    groups.push({
      fromNode: flatten.id,
      operation: flatten.label ?? 'Flatten',
      pieces: [
        {
          pieceId: `${flatten.id}-board`,
          species: 'mixed',
          quantity: 1,
          thickness: dim(dims.thickness),
          width: dim(dims.width),
          length: dim(dims.length),
          machineSetting: {
            machine: 'drum-sander',
            targetThickness: dim(dims.thickness),
            passCount: passCount * 2,
            perPass: dim(shop.drumSanderRemovalPerPass),
          },
        },
      ],
    });
  }

  /* ---- Summary ----------------------------------------------------------- */

  const inputVolume = sum(Object.values(evaluated.ledger.input));
  const finishedVolume =
    toInches(dims.width) * toInches(dims.length) * toInches(dims.thickness);
  const waste =
    sum(Object.values(evaluated.ledger.kerf)) +
    sum(Object.values(evaluated.ledger.removed)) +
    sum(Object.values(evaluated.ledger.offcut));

  return {
    boardName: options.name,
    finished: { width: dim(dims.width), length: dim(dims.length), thickness: dim(dims.thickness) },
    purchase,
    groups,
    ledger: buildLedger(graph, evaluated, shop),
    summary: {
      totalBoardFeet: purchase.reduce((s, p) => s + p.boardFeet, 0),
      endGrainMultiplier: finishedVolume > 0 ? inputVolume / finishedVolume : 0,
      wasteFraction: inputVolume > 0 ? waste / inputVolume : 0,
    },
  };
}

function extentX(w: { crossSection: { outline: readonly { x: number; y: number }[] } }): number {
  const xs = w.crossSection.outline.map((p) => p.x);
  return Math.max(...xs) - Math.min(...xs);
}

function extentY(w: { crossSection: { outline: readonly { x: number; y: number }[] } }): number {
  const ys = w.crossSection.outline.map((p) => p.y);
  return Math.max(...ys) - Math.min(...ys);
}

function sum(values: readonly number[]): number {
  return values.reduce((s, v) => s + v, 0);
}

/** Render a cut list as plain text, for the printed sheet and for tests. */
export function formatCutList(list: CutList): string {
  const out: string[] = [];
  out.push(`${list.boardName}`);
  out.push(
    `Finished: ${formatTicks(list.finished.width.asMeasured)} × ` +
      `${formatTicks(list.finished.length.asMeasured)} × ` +
      `${formatTicks(list.finished.thickness.asMeasured)}`,
  );
  out.push('');
  out.push('SHOPPING LIST');
  for (const line of list.purchase) {
    out.push(
      `  ${line.displayName.padEnd(16)} ${line.boardFeet.toFixed(2).padStart(6)} bd ft   ` +
        `(${formatTicks(line.rough.thickness)} × ${formatTicks(line.rough.width)} × ${formatTicks(line.rough.length)})`,
    );
  }
  out.push(`  ${'TOTAL'.padEnd(16)} ${list.summary.totalBoardFeet.toFixed(2).padStart(6)} bd ft`);
  out.push('');
  out.push('CUT LIST');
  for (const group of list.groups) {
    out.push(`  ${group.operation}`);
    for (const piece of group.pieces) {
      const setting = describeSetting(piece.machineSetting);
      out.push(
        `    ${String(piece.quantity).padStart(3)} ×  ` +
          `${formatTicks(piece.thickness.asMeasured)} × ${formatTicks(piece.width.asMeasured)} × ${formatTicks(piece.length.asMeasured)}` +
          (setting ? `   [${setting}]` : ''),
      );
    }
  }
  return out.join('\n');
}

export function describeSetting(setting: MachineSetting | undefined): string {
  if (!setting) return '';
  switch (setting.machine) {
    case 'tablesaw-rip':
      return (
        `fence ${formatTicks(setting.fenceSetting.asMeasured)}` +
        (setting.bevel === 0
          ? ''
          : `, bevel ${(setting.bevel / 1000).toFixed(1)}° tilted away from the fence`)
      );
    case 'sled-crosscut':
      return `stop block ${formatTicks(setting.stopBlockSetting.asMeasured)}, ${setting.count} slices`;
    case 'drum-sander':
      return `to ${formatTicks(setting.targetThickness.asMeasured)}, about ${setting.passCount} passes`;
  }
}
